### ISSUE TITLE
Warning related to PropTypes

### ISSUE THREAD

**Issue by nsisodiya** [nsisodiya/react-json-viewer#11]
```proxyConsole.js:56 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.```

**Comment by mcguiretj** [comment]
Not sure if you need this or not. React seperated Proptypes into another package. You can see this note here: https://facebook.github.io/react/docs/typechecking-with-proptypes.html npm install --save prop-types

**Comment by nsisodiya** [comment]
Would be great if you make a pull request. I think it is easy to remove.

**Comment by bvenkatr** [comment]
Hi @nsisodiya , I am working on it, I have chnged to prop-types, but facing some issue with webpack build. will generate PR soon.

**Comment by nsisodiya** [comment]
done by latest pull merge.
