### ISSUE TITLE
Preinstall npm prune is causing issues

### ISSUE THREAD

**Issue by sairamkrish** [nsisodiya/react-json-viewer#8]
Hi

I am using react-json-viewer and it's very useful. Facing one problem. In package.json -> preinstall, npm prune is specified. This is causing intermittent issues in jenkins. This is caused only in react-json-viewer project. It is cleaning up webpack etc which is needed for the project. 

Is this wrong to have npm prune in preinstall ?

**Comment by nsisodiya** [comment]
# Thanks for using react-json-viewer,

`npm prune` make sure that your node-modules folder should not have unwanted packages !! I guess, it is needed. We also use in our project but never faced such problem.

If it clean `webpack` etc than you should included those in packages in `dev-dependencies` !!

Let me know !!

**Comment by gravitycode** [comment]
It doesnt work with Jenkins. 

```
npm ERR! react-json-viewer@1.6.0 postinstall: `npm outdated`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-json-viewer@1.6.0 postinstall script 'npm outdated'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-json-viewer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm outdated
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-json-viewer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-json-viewer
npm ERR! There is likely additional logging output above.

```

**Comment by nsisodiya** [comment]
I will fix tomorrow.

**Comment by nsisodiya** [comment]
I have released react-json-viewer@1.6.1 where I have removed things which causing errors. Please test. I am closing issue, Please feel free to complain your problems here or at my email narendra@billexo.com

**Comment by gravitycode** [comment]
Thank you @nsisodiya. I want to test but i can´t see the v1.6.1. Have you uploaded the versión?

**Comment by nsisodiya** [comment]
It is there - Please check - https://www.npmjs.com/package/react-json-viewer

**Comment by gravitycode** [comment]
@nsisodiya Sorry, my cache repository was playing with me. Now its works perfectly. Thank you for your effort!
